<?php
/**
 * @file
 * Code for the kkb_base feature.
 */

include_once 'kkb_base.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function kkb_base_form_node_form_alter(&$form, $form_state) {
  if ($form['#node']->type == 'ding_event' &&
    empty($form['#node']-> nid)) {
    // Set default tab to Scheduler options when creating new events as
    // unpublish date is a required field.
    // @see http://dropbucket.org/node/332
    $form['additional_settings']['#default_tab'] = 'edit-scheduler-settings';
  }
}
