<?php
/**
 * @file
 * Code for the KKB newsletter paragraphs feature.
 */

include_once 'kkb_newsletter_paragraphs.features.inc';

/**
 * Implements hook_theme().
 */
function kkb_newsletter_paragraphs_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['paragraphs_item__kkb_newsletter_reference'] = array(
    'render element' => 'elements',
    'base hook' => 'paragraphs_item',
    'template' => 'paragraphs-item--kkb-newsletter-reference',
    'path' => drupal_get_path('module', 'kkb_newsletter_paragraphs') . '/templates',
  );
  return $theme;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function kkb_newsletter_paragraphs_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Define the newsletter paragraph roles.
 */
function kkb_newsletter_paragraphs_secure_permissions_roles() {
  return array(
    'newsletter paragraphs administrator'
  );
}

/**
 * Define site permissions for the newsletter paragraphs.
 */
function kkb_newsletter_paragraphs_secure_permissions($role) {
  $permissions = array(
    'administrators' => array(
      'create newsletter_administration content',
      'edit any newsletter_administration content',
      'delete any newsletter_administration content',
    ),
    'newsletter paragraphs administrator' => array(
      'create newsletter_administration content',
      'edit any newsletter_administration content',
      'delete any newsletter_administration content',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Revert features.
 */
function kkb_newsletter_paragraphs_update_7102() {
  features_revert_module('kkb_newsletter_paragraphs');
  features_revert_module('ding_news');
  features_revert_module('ding_page');
  features_revert_module('ding_event');
}
