<?php

/**
 * @file
 * Code for the KKB Event feature.
 */

include_once 'kkb_event.features.inc';

/**
 * Implements hook_preprocess_views_view().
 */
function kkb_event_preprocess_views_view(&$vars) {
  switch ($vars['name']) {
    case 'kkb_event':
      if ($vars['view']->current_display == 'ding_event_list_frontpage') {
        drupal_add_css(drupal_get_path('module', 'kkb_event') . '/css/kkb_event.css');
        // Add slide-on-mobile class.
        $vars['classes_array'][] = 'slide-on-mobile';
        // Add first-child-large class.
        $vars['classes_array'][] = 'first-child-large';
      }
      break;
  }
}
