<?php

/**
 * @file
 * Code for the KKB Help feature.
 */

include_once 'kkb_help.features.inc';

/**
 * Implements hook_theme().
 */
function kkb_help_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__ding_help_page'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--ding-help-page',
    'path' => drupal_get_path('module', 'kkb_help') . '/templates',
  );

  $theme['node__ding_help_front'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--ding-help-front',
    'path' => drupal_get_path('module', 'kkb_help') . '/templates',
  );

  $theme['taxonomy_term__help_category'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'taxonomy-term--help-category',
    'path' => drupal_get_path('module', 'kkb_help') . '/templates',
  );
  return $theme;
}

/**
 * Node preprocess function.
 */
function kkb_help_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'full' &&
    in_array($variables['type'], array('ding_help_page', 'ding_help_front'))) {
    drupal_add_css(drupal_get_path('module', 'kkb_help') . '/css/kkb_help.css');

    if ($variables['type'] == 'ding_help_page') {

      $wrapper = entity_metadata_wrapper('node', $variables['node']);

      $breadcrumb = array();

      $breadcrumb[] = _kkb_help_top_breadcrumb($wrapper->language->value());

      $term = $wrapper->field_ding_help_page_category->value();
      $uri = entity_uri('taxonomy_term', $term);
      $breadcrumb[] = l($term->name, $uri['path'], $uri['options']);

      $breadcrumb[] = drupal_get_title();

      // Set Breadcrumbs.
      drupal_set_breadcrumb($breadcrumb);
    }
  }
}

/**
 * Term preprocess function.
 */
function kkb_help_preprocess_taxonomy_term(&$variables) {
  if ($variables['view_mode'] == 'full' &&
    $variables['vocabulary_machine_name'] == 'help_category') {
    drupal_add_css(drupal_get_path('module', 'kkb_help') . '/css/kkb_help.css');
    $term = $variables['term'];
    $breadcrumb = array();
    $breadcrumb[] = _kkb_help_top_breadcrumb($term->language);
    $breadcrumb[] = $term->name;

    drupal_set_breadcrumb($breadcrumb);
  }
}

/**
 * Get the breadcrumb item for the help front page.
 */
function _kkb_help_top_breadcrumb($language) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'ding_help_front')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('language', $language);

  $res = $query->execute();
  if (!empty($res['node'])) {
    $nids = array_keys($res['node']);
    $front_node = node_load(reset($nids));
    $uri = entity_uri('node', $front_node);
    return l($front_node->title, $uri['path'], $uri['options']);
  }
  // Fallback in case we can't find a help front page in the current
  // language.
  return t('Help');
}

/**
 * Field preprocess function.
 */
function kkb_help_preprocess_field(&$variables) {
  // Replace field label with value from field_ding_help_page_files_title if it
  // is set.
  if ($variables['element']['#field_name'] == 'field_ding_help_page_files') {
    $wrapper = entity_metadata_wrapper('node', $variables['element']['#object']);
    $title = $wrapper->field_ding_help_page_files_title->value();
    if (!empty($title)) {
      $variables['label'] = check_plain($title);
    }
  }
}

/**
 * Entity preprocess function.
 */
function kkb_help_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    $wrapper = entity_metadata_wrapper('paragraphs_item', $variables['paragraphs_item']);

    switch ($wrapper->getBundle()) {
      case 'ding_help_page_accordion':
        $body = $wrapper->field_ding_help_p_a_body->value();
        // Overwrite content with collapsible.
        $variables['content'] = array(
          '#type' => 'fieldset',
          '#title' => $wrapper->field_ding_help_p_a_title->value(),
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
          // The above is not enough to get collapsibles working (core bug), so
          // add attributes and JS.
          '#attributes' => array('class' => array('collapsible', 'collapsed')),
          '#attached' => array('js' => array('misc/collapse.js', 'misc/form.js')),
          'body' => array(
            '#markup' => check_markup($body['value'], $body['format']),
          ),
        );
        break;

      case 'ding_help_front_box':
        // Make term name a headline.
        $variables['content']['field_ding_help_p_b_category'][0]['#prefix'] = '<h3>';
        $variables['content']['field_ding_help_p_b_category'][0]['#suffix'] = '</h3>';
        // Add show more link.
        if ($wrapper->field_ding_help_p_b_show_more->value()) {
          $uri = entity_uri('taxonomy_term', $wrapper->field_ding_help_p_b_category->value());
          $uri['options']['attributes']['class'][] = 'help-more-link';
          $variables['content']['link'] = array(
            '#theme' => 'link',
            // Should be last in list.
            '#weight' => 100,
            '#text' => t('More help pages'),
            '#path' => $uri['path'],
            // DDBasic fails if attributes is not set.
            '#options' => $uri['options'],
          );
        }
        break;

      case 'ding_help_page_cta':
        $variables['content']['#prefix'] = '<div class="more-link">';
        $variables['content']['#suffix'] = '</div>';
        break;
    }
  }
}
