<?php

/**
 * @file
 * Adds button to material to find it physically at the library.
 */

/**
 * Implements hook_menu().
 */
function kkb_wayfinder_menu() {
  $items['admin/config/ding/wayfinder'] = array(
    'title' => 'Wayfinder settings',
    'description' => 'Manage wayfinder branch mapping.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kkb_wayfinder_admin_form'),
    'access arguments' => array('administer ding provider'),
    'file' => 'kkb_wayfinder.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function kkb_wayfinder_theme() {
  return array(
    'kkb_wayfinder_button' => array(
      'template' => 'templates/kkb-wayfinder-button',
      'variables' => array(
        'type' => NULL,
        'value' => NULL,
        'title' => NULL,
        'value_title' => FALSE,
        'options' => FALSE,
      ),
    ),
  );
}

/**
 * Implements hook_ding_entity_buttons().
 */
function kkb_wayfinder_ding_entity_buttons($type, $entity) {
  if ($type == 'ding_entity' && variable_get('kkb_wayfinder_url', '')) {
    $return = array();

    $branches = variable_get('kkb_wayfinder_branches', array());

    $availability = ding_availability_holdings(array($entity->localId));
    $options = array();
    foreach ($availability[$entity->localId]['holdings'] as $holding) {
      if ($holding['available_count'] > 0 && isset($branches[drupal_strtolower($holding['placement'][0])])) {
        $options[] = array(
          'custom' => array(
            // DDBasic styling forces us to do it like this.
            'title' => '<div class="list-title">' . $holding['placement'][0] . '</div>',
            'href' => '#',
            'html' => TRUE,
            'attributes' => array(
              'class' => array(),
              'data-wayfinder-faust' => $entity->localId,
              'data-wayfinder-branch' => $branches[drupal_strtolower($holding['placement'][0])],
            ),
          ),
        );
      }
    }
    if ($options) {
      $return[] = array(
        '#theme' => 'kkb_wayfinder_button',
        '#title' => t('See on map'),
        '#value' => $entity->ding_entity_id,
        '#options' => $options,
      );
    }
    return $return;
  }
}

/**
 * Preprocess kkb_wayfinder_button.
 */
function template_preprocess_kkb_wayfinder_button(&$variables) {
  $variables['classes_array'] = array(
    'kkb-wayfinder--button',
    // Legacy: Use classes from now obsolete ding_list module.
    // Buttons with multiple actions are no longer supported but we still need
    // the functionality here to display multiple libraries in an intelligent
    // manner. Consequently we reuse the classes and the JS and CSS from Ding 5.
    'ding-list-add-button',
    'ding-list-add-button--multiple-actions'
  );
  if (empty($variables['title'])) {
    $variables['title'] = t('See on map');
  }

  $variables['buttons'] = array(
    '#theme' => 'links',
    '#links' => array(),
    '#attributes' => array(
      'class' => array('buttons'),
    ),
    '#attached' => array(
      'library' => array(array('system', 'drupal.ajax')),
      'css' => array(
        drupal_get_path('module', 'kkb_wayfinder') . '/css/kkb_wayfinder.buttons.min.css',
        drupal_get_path('module', 'kkb_wayfinder') . '/css/kkb_wayfinder.css',
      ),
      'js' => array(
        drupal_get_path('module', 'kkb_wayfinder') . '/js/kkb_wayfinder.buttons.js',
        drupal_get_path('module', 'kkb_wayfinder') . '/js/kkb_wayfinder.js',
        array(
          'data' => variable_get('kkb_wayfinder_url', ''),
          'type' => 'external',
        ),
      ),
    ),
  );

  $variables['single_link'] = FALSE;

  $options = $variables['options'];
  foreach ($options as $option) {
    $variables['buttons']['#links'][] = $option['custom'];
  }
}
