<?php

/**
 * @file
 * Code for the Ding FAQ feature.
 */

include_once 'ding_faq.features.inc';

/**
 * Implements hook_theme().
 *
 * Override DDBasic's template for faq questions. It assumes there's
 * field_groups that's not there.
 */
function ding_faq_theme() {
  return array(
    'node__ding_faq_question__override' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--ding-faq-question--override',
      'path' => drupal_get_path('module', 'ding_faq') . '/templates',
    ),
  );
}

/**
 * Implements hook_preprocess_node().
 */
function ding_faq_preprocess_node(&$variables) {
  if ($variables['node']->type == 'ding_faq_question') {
    $variables['theme_hook_suggestions'][] = 'node__ding_faq_question__override';
  }
}

/**
 * Implements hook_views_post_render().
 */
function ding_faq_views_pre_render(&$view, &$output, &$cache) {
  if ($view->name == 'ding_faq') {
    drupal_add_css(drupal_get_path('module', 'ding_faq') . '/css/ding_faq.css');
  }
}
