<?php
/**
 * @file
 * Code for the KKB Frontpage Promotions feature.
 */

include_once 'kkb_frontpage_promotions.features.inc';


/**
 * Implements hook_preprocess_html().
 */
function kkb_frontpage_promotions_preprocess_html(&$variables) {
  if (!empty($GLOBALS['kkb_promotion']) && $GLOBALS['kkb_promotion'] == TRUE) {
    $variables['classes_array'][] = 'has-kkb-promotion';
    $css_path = drupal_get_path('module', 'kkb_frontpage_promotions') . '/kkb-frontpage-promotions.css';
    drupal_add_css($css_path, array('group' => CSS_THEME, 'weight' => 115));
  }

}

function kkb_frontpage_promotions_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_image' && $variables['element']['#bundle'] == 'field_links') {
    $variables['label_hidden'] = TRUE;
  }
  if ($variables['element']['#field_name'] == 'field_links') {
    $variables['label_hidden'] = TRUE;

    $ul_image_links = '<ul>';

    foreach ($variables['items'] as $item => $value) {
      $field_collection_item = reset($value['entity']['field_collection_item']);
      $link_url = $field_collection_item['field_link'][0]['#element']['url'];

      $image_uri = $field_collection_item['field_image'][0]['#item']['uri'];
      $image_url = file_create_url($image_uri);

      $image_title = $field_collection_item['field_image'][0]['#item']['title'];
      $image_alt = $field_collection_item['field_image'][0]['#item']['alt'];

      $img_variables = array(
        'path' => $image_url,
        'alt' => $image_alt,
        'title' => $image_title,
        'attributes' => array(),
      );

      $img = theme_image($img_variables);

      $ul_image_links .= '<li><a href="' . $link_url . '">' . $img . '</a></li>';
    }

    $ul_image_links .= '</ul>';

    $variables['ul_image_links'] = $ul_image_links;

  }
}

function kkb_frontpage_promotions_preprocess_panels_pane(&$variables) {

  if ($variables['pane']->subtype == 'frontpage_promotion-panel_pane_1') {
    $GLOBALS['kkb_promotion'] = TRUE;
  }
}

function kkb_frontpage_promotions_preprocess_node(&$variables, $hook) {
  if ($variables['type'] == 'promotion') {

    if (!empty($variables['field_background_image'][0]['uri'])) {
      $image_uri = $variables['field_background_image'][0]['uri'];
      $bg_image_url = file_create_url($image_uri);
      $variables['bg_style'] = 'style="background-image: url(' . $bg_image_url . ');"';
    }

    if (!empty($variables['field_indentation'][0]['value'])) {
      $indentation = $variables['field_indentation'][0]['value'];
      $variables['indentation_style'] = 'style="padding-left:' . $indentation . 'px;"';
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function kkb_frontpage_promotions_theme_registry_alter(&$theme_registry) {
	// Defined path to the current module.
	$module_path = drupal_get_path('module', 'kkb_frontpage_promotions');
	// Find all .tpl.php files in this module's folder recursively.
	$template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
	// Iterate through all found template file objects.
	foreach ($template_file_objects as $key => $template_file_object) {
		// If the template has not already been overridden by a theme.
		if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
			// Alter the theme path and template elements.
			$theme_registry[$key]['theme path'] = $module_path;
			$theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
			$theme_registry[$key]['type'] = 'module';
		}
	}
}
